### ISSUE TITLE
awaitMessages function doesn't work properly

### ISSUE THREAD

**Issue by EmWhyKay** [minemidnight/eris-additions#23]
It did work well when I first used it, but it didn't work properly for the second (or others).

The code I use:
`let collected = await msg.channel.awaitMessages(x => x.content.length > 0 && x.author.id === msg.author.id, { time: 60000, maxMatches: 1 });`

![Ekran Alıntısı](https://user-images.githubusercontent.com/39646922/109979303-cbac9a00-7d0f-11eb-8ef9-401215905373.PNG)

**Comment by minemidnight** [comment]
old & nobody else has issue?
